import { Job } from './types'

export const SAMPLE_JOBS: Job[] = [
  {
    id: 'job-001',
    title: 'Senior Software Engineer',
    company: 'TechVision AI',
    location: 'San Francisco, CA',
    type: 'full-time',
    salary: { min: 150000, max: 200000, currency: 'USD' },
    description: 'Join our AI team to build next-generation machine learning platforms. You\'ll work on cutting-edge technology and collaborate with world-class engineers.',
    requirements: [
      '5+ years of software development experience',
      'Strong proficiency in Python and JavaScript',
      'Experience with ML frameworks (TensorFlow, PyTorch)',
      'Excellent problem-solving skills',
    ],
    idealTraits: [
      { trait: 'openness', weight: 0.4, minScore: 70 },
      { trait: 'conscientiousness', weight: 0.35, minScore: 65 },
      { trait: 'extraversion', weight: 0.15, minScore: 40 },
      { trait: 'agreeableness', weight: 0.1, minScore: 50 },
    ],
    tags: ['AI', 'Machine Learning', 'Python', 'Remote Friendly'],
    postedAt: '2026-02-01T00:00:00Z',
    deadline: '2026-03-15T00:00:00Z',
    logo: '🤖',
  },
  {
    id: 'job-002',
    title: 'Product Manager',
    company: 'InnovateCo',
    location: 'New York, NY',
    type: 'full-time',
    salary: { min: 130000, max: 170000, currency: 'USD' },
    description: 'Lead product strategy for our flagship SaaS platform. Drive roadmap, collaborate with engineering, and shape the future of enterprise software.',
    requirements: [
      '3+ years of product management experience',
      'Strong analytical and communication skills',
      'Experience with agile methodologies',
      'Technical background preferred',
    ],
    idealTraits: [
      { trait: 'extraversion', weight: 0.35, minScore: 65 },
      { trait: 'conscientiousness', weight: 0.3, minScore: 70 },
      { trait: 'openness', weight: 0.2, minScore: 60 },
      { trait: 'agreeableness', weight: 0.15, minScore: 55 },
    ],
    tags: ['Product', 'SaaS', 'Leadership', 'Strategy'],
    postedAt: '2026-02-05T00:00:00Z',
    deadline: '2026-03-01T00:00:00Z',
    logo: '📊',
  },
  {
    id: 'job-003',
    title: 'UX Designer',
    company: 'DesignLab Studio',
    location: 'Remote',
    type: 'remote',
    salary: { min: 90000, max: 130000, currency: 'USD' },
    description: 'Create beautiful, intuitive user experiences. Work with cross-functional teams to design products that users love.',
    requirements: [
      '3+ years of UX design experience',
      'Proficiency in Figma and design systems',
      'Strong portfolio showcasing user-centered design',
      'Experience with user research',
    ],
    idealTraits: [
      { trait: 'openness', weight: 0.45, minScore: 75 },
      { trait: 'agreeableness', weight: 0.25, minScore: 60 },
      { trait: 'conscientiousness', weight: 0.2, minScore: 55 },
      { trait: 'extraversion', weight: 0.1, minScore: 45 },
    ],
    tags: ['Design', 'UX', 'Figma', 'Remote'],
    postedAt: '2026-02-08T00:00:00Z',
    deadline: '2026-03-20T00:00:00Z',
    logo: '🎨',
  },
  {
    id: 'job-004',
    title: 'Customer Success Manager',
    company: 'CloudServe Inc',
    location: 'Austin, TX',
    type: 'full-time',
    salary: { min: 80000, max: 110000, currency: 'USD' },
    description: 'Be the voice of our customers! Drive adoption, reduce churn, and build lasting relationships with enterprise clients.',
    requirements: [
      '2+ years in customer success or account management',
      'Excellent communication and relationship skills',
      'Experience with CRM tools (Salesforce, HubSpot)',
      'Problem-solving mindset',
    ],
    idealTraits: [
      { trait: 'agreeableness', weight: 0.4, minScore: 75 },
      { trait: 'extraversion', weight: 0.35, minScore: 70 },
      { trait: 'conscientiousness', weight: 0.15, minScore: 55 },
      { trait: 'neuroticism', weight: 0.1, minScore: 0 }, // Lower is better for stress
    ],
    tags: ['Customer Success', 'SaaS', 'Account Management'],
    postedAt: '2026-02-10T00:00:00Z',
    deadline: '2026-02-28T00:00:00Z',
    logo: '🤝',
  },
  {
    id: 'job-005',
    title: 'Data Scientist',
    company: 'QuantumData Labs',
    location: 'Boston, MA',
    type: 'full-time',
    salary: { min: 140000, max: 180000, currency: 'USD' },
    description: 'Turn data into insights! Build predictive models, analyze complex datasets, and drive data-informed decisions.',
    requirements: [
      'MS/PhD in Statistics, Math, or related field',
      'Expert in Python, R, and SQL',
      'Experience with big data technologies',
      'Strong statistical modeling skills',
    ],
    idealTraits: [
      { trait: 'openness', weight: 0.35, minScore: 65 },
      { trait: 'conscientiousness', weight: 0.4, minScore: 75 },
      { trait: 'extraversion', weight: 0.1, minScore: 35 },
      { trait: 'agreeableness', weight: 0.15, minScore: 45 },
    ],
    tags: ['Data Science', 'Python', 'Machine Learning', 'Statistics'],
    postedAt: '2026-02-03T00:00:00Z',
    deadline: '2026-03-10T00:00:00Z',
    logo: '📈',
  },
  {
    id: 'job-006',
    title: 'Sales Representative',
    company: 'GrowthForce',
    location: 'Chicago, IL',
    type: 'full-time',
    salary: { min: 60000, max: 120000, currency: 'USD' },
    description: 'Join our high-energy sales team! Drive revenue, build pipelines, and close deals with B2B clients.',
    requirements: [
      '1+ years of sales experience',
      'Strong negotiation and closing skills',
      'Excellent presentation abilities',
      'Self-motivated and goal-oriented',
    ],
    idealTraits: [
      { trait: 'extraversion', weight: 0.45, minScore: 75 },
      { trait: 'conscientiousness', weight: 0.25, minScore: 60 },
      { trait: 'agreeableness', weight: 0.15, minScore: 50 },
      { trait: 'neuroticism', weight: 0.15, minScore: 0 },
    ],
    tags: ['Sales', 'B2B', 'Commission', 'Growth'],
    postedAt: '2026-02-09T00:00:00Z',
    deadline: '2026-02-25T00:00:00Z',
    logo: '💼',
  },
  {
    id: 'job-007',
    title: 'DevOps Engineer',
    company: 'ScaleUp Tech',
    location: 'Seattle, WA',
    type: 'full-time',
    salary: { min: 130000, max: 170000, currency: 'USD' },
    description: 'Build and maintain our cloud infrastructure. Automate deployments, ensure reliability, and optimize performance.',
    requirements: [
      '4+ years of DevOps/SRE experience',
      'Expert in AWS/GCP/Azure',
      'Strong knowledge of Kubernetes and Docker',
      'Experience with CI/CD pipelines',
    ],
    idealTraits: [
      { trait: 'conscientiousness', weight: 0.45, minScore: 75 },
      { trait: 'openness', weight: 0.25, minScore: 55 },
      { trait: 'neuroticism', weight: 0.2, minScore: 0 },
      { trait: 'agreeableness', weight: 0.1, minScore: 45 },
    ],
    tags: ['DevOps', 'AWS', 'Kubernetes', 'Automation'],
    postedAt: '2026-02-06T00:00:00Z',
    deadline: '2026-03-05T00:00:00Z',
    logo: '⚙️',
  },
  {
    id: 'job-008',
    title: 'Marketing Manager',
    company: 'BrandWave Agency',
    location: 'Los Angeles, CA',
    type: 'full-time',
    salary: { min: 95000, max: 130000, currency: 'USD' },
    description: 'Lead marketing campaigns that drive growth. Manage brand strategy, content, and performance marketing.',
    requirements: [
      '4+ years of marketing experience',
      'Experience with digital marketing channels',
      'Strong creative and analytical skills',
      'Team leadership experience',
    ],
    idealTraits: [
      { trait: 'openness', weight: 0.35, minScore: 70 },
      { trait: 'extraversion', weight: 0.3, minScore: 65 },
      { trait: 'conscientiousness', weight: 0.2, minScore: 60 },
      { trait: 'agreeableness', weight: 0.15, minScore: 55 },
    ],
    tags: ['Marketing', 'Digital', 'Brand', 'Leadership'],
    postedAt: '2026-02-07T00:00:00Z',
    deadline: '2026-03-01T00:00:00Z',
    logo: '📢',
  },
  {
    id: 'job-009',
    title: 'Research Scientist',
    company: 'BioTech Innovations',
    location: 'San Diego, CA',
    type: 'full-time',
    salary: { min: 120000, max: 160000, currency: 'USD' },
    description: 'Conduct cutting-edge research in computational biology. Publish papers and drive scientific breakthroughs.',
    requirements: [
      'PhD in Biology, Bioinformatics, or related field',
      'Strong publication record',
      'Experience with lab techniques and computational methods',
      'Excellent scientific writing skills',
    ],
    idealTraits: [
      { trait: 'openness', weight: 0.45, minScore: 80 },
      { trait: 'conscientiousness', weight: 0.35, minScore: 70 },
      { trait: 'extraversion', weight: 0.1, minScore: 30 },
      { trait: 'agreeableness', weight: 0.1, minScore: 50 },
    ],
    tags: ['Research', 'BioTech', 'Science', 'PhD'],
    postedAt: '2026-02-02T00:00:00Z',
    deadline: '2026-03-30T00:00:00Z',
    logo: '🔬',
  },
  {
    id: 'job-010',
    title: 'HR Coordinator',
    company: 'PeopleFirst HR',
    location: 'Denver, CO',
    type: 'full-time',
    salary: { min: 55000, max: 75000, currency: 'USD' },
    description: 'Support our HR operations. Manage onboarding, coordinate recruitment, and foster a positive workplace culture.',
    requirements: [
      '1+ years of HR experience',
      'Strong interpersonal skills',
      'Experience with HRIS systems',
      'Detail-oriented and organized',
    ],
    idealTraits: [
      { trait: 'agreeableness', weight: 0.4, minScore: 75 },
      { trait: 'conscientiousness', weight: 0.3, minScore: 65 },
      { trait: 'extraversion', weight: 0.2, minScore: 55 },
      { trait: 'neuroticism', weight: 0.1, minScore: 0 },
    ],
    tags: ['HR', 'Recruiting', 'People Ops', 'Entry Level'],
    postedAt: '2026-02-11T00:00:00Z',
    deadline: '2026-02-28T00:00:00Z',
    logo: '👥',
  },
]



